-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

--###############
--## MONITORS ###
--###############

hl.monitor({
  output = "",
  mode = "1920x1080",
  position = "auto",
  scale = "1",
})

--##############
--## DEVICE ####
--##############

hl.device({
  name = "epic-mouse-v1",
  sensitivity = -0.5,
})

-- Locale
hl.env("LANGUAGE", "de")
hl.env("LANG", "de_DE.UTF-8")

-- Qt
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_STYLE_OVERRIDE", "kvantum")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")

-- GTK
hl.env("GDK_DEBUG", "portals")
hl.env("GTK_USE_PORTAL", "1")

-- Desktop
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- NVIDIA (https://wiki.hyprland.org/Nvidia/)
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("GBM_BACKEND", "nvidia-drm")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("WLR_NO_HARDWARE_CURSORS", "1")

-- Other
hl.env("NVD_BACKEND", "direct")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")



hl.bind("ALT + Q", hl.dsp.window.close())
hl.config({
    misc = {
        disable_hyprland_logo = true,
    },
    animations = {
        enabled = false,
    },
    cursor = {
    no_hardware_cursors = true,
    },
})

hl.on("hyprland.start", function()
    hl.exec_cmd("nwg-hello; hyprctl dispatch exit")
end)

